variable prod_desired_size {}
variable prod_environment {}
variable prod_http_put_response_hop_limit {}
variable prod_http_tokens {}
variable prod_instance_types {}
variable prod_max_size {}
variable prod_min_size {}
variable prod_name {}
variable prod_node_group_name {}
variable prod_eks_version {}
variable prod_launch_template_resource_type {}