variable prod_desired_size {}
variable prod_ec2_ssh_key {}
variable prod_environment {}
variable prod_instance_types {}
variable prod_max_size {}
variable prod_min_size {}
variable prod_name {}
variable prod_node_group_name {}
variable prod_version {}